export const managers = [
  {
    team: "기획팀",
    isHead: true,
    major: "국어국문학과",
    name: "이예은",
    account: "@y_eun07",
    id: 0,
  },
  {
    team: "기획팀",
    isHead: false,
    major: "국악과",
    name: "이지수",
    account: "@ljspraysun",
    id: 1,
  },
  {
    team: "기획팀",
    isHead: false,
    major: "서어서문학과",
    name: "최지민",
    account: "@jimmmin___",
    id: 2,
  },
];

export const designers = [
  {
    team: "디자인팀",
    isHead: false,
    major: "미학과",
    name: "박수빈",
    account: "@s4xd4d3",
    id: 5,
  },
  {
    team: "디자인팀",
    isHead: false,
    major: "금속공예과",
    name: "박미란",
    account: "@mirannaranna",
    id: 4,
  },
  {
    team: "디자인팀",
    isHead: true,
    major: "사회학과",
    name: "배정은",
    account: "bje0305@snu.ac.kr",
    id: 3,
  },
];

export const developers = [
  {
    team: "개발팀",
    isHead: false,
    major: "자유전공학부",
    name: "주혜현",
    account: "@vermilion_sol",
    id: 6,
    period: "2023-1 ~ 2024-1",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "자유전공학부",
    name: "김민지",
    account: "@kiminji000",
    id: 7,
    period: "2023-1 ~ 2024-1",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "전기정보공학부",
    name: "박준영",
    account: "@partlyjadedyouth",
    id: 8,
    period: "2023-1 ~ 2024-1",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "전기정보공학부",
    name: "이서현",
    account: "@seohyun___lee",
    id: 6,
    period: "2023-1 ~ 2023-2",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "",
    name: "장준석",
    account: "newtonjjang@naver.com",
    id: 9,
    period: "2024-1",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "",
    name: "백창인",
    account: "@bbaekcloud",
    id: 10,
    period: "2024-1 ~ 2024-2",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "전기정보공학부",
    name: "지명금",
    account: "@bright_gold_j",
    id: 11,
    period: "2024-2 ~ 2025-1",
  },
  {
    team: "개발팀",
    isHead: false,
    major: "식품동물생명공학부",
    name: "박현서",
    account: "@hnso000",
    id: 12,
    period: "2025-1",
  },
];
